name: Playlist-Generator workflow

on:
  schedule:
    - cron: "* * * * *" # Example: Run every minute
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Run updater script
        run: |
          python3 main.py

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add playlists
          git commit -m "Updated via AutoBot 🤖" || echo "No changes to commit"
          git push https://github.com/TeamToxicIN/test/ HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

